<?xml version="1.0" encoding="utf-8"?>
<openerp>
  <data noupdate="0">

        <!--Email template-->
        <record id="email_template_send_to_braintec" model="mail.template">
            <field name="name">Send auto email to brain-tec AG</field>
            <field name="email_from">${ctx.get('email_from')}</field>
            <field name="subject">Company '${ctx.get('companyname')}' has a problem with brain-tec Odoo Salary</field>
            <field name="email_to">odoo+swissdec@braintec-group.com</field>
            <field name="model_id" ref="bt_swissdec.model_bt_swissdec_transmitter"/>
            <field name="auto_delete" eval="False"/>
            <field name="body_html"><![CDATA[
<div style="font-family: 'Lucica Grande', Ubuntu, Arial, Verdana, sans-serif; font-size: 12px; color: rgb(34, 34, 34); background-color: rgb(255, 255, 255); ">
    An error has occurred. Here are the details: <br>
    <ul>
        <li>DB: ${ctx.get('dbname')} <br></li>
        <li>Error: ${ctx.get('error_in_declare')} <br></li>
        <li>User: ${ctx.get('username')} (${ctx.get('userid')}) <br></li>
        <li>Object: ${ctx.get('object')} <br></li>
        <li>ObjectID: ${ctx.get('object_id')}<br></li>
        <li><a target="_blank" href=${ctx.get('link')}>${ctx.get('link_name')}</a></li>
    </ul>
</div>
            ]]></field>
        </record>
  
  </data>
</openerp>